### ISSUE TITLE
群功能启用

### ISSUE THREAD

**Issue by bigqlmz** [VatinaCharo/PicPlug#2]
模式选择：
1、群白名单模式
2、全部群启用gkd功能的开关

**Comment by VatinaCharo** [comment]
目前插件就是设定的群白名单模式，应该不会添加全部群启用的功能，为了避免打扰到不该发图的群，比如说有人在班级群之类的地方误触发了指令。

单独的指令开关在做了，在做了。

**Comment by VatinaCharo** [comment]
目前已经做好了单独的指令控制开关，可以在配置文件里设置是否启用某个指令

虽然比较粗暴，是全局开关，但感觉上已经足够好用了，就先这样吧
